# Generated by Django 2.0.3 on 2018-04-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakinglyricsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bands',
        ),
    ]
