language: python
python:
  - '3.6'
install: "pip install -r requirements/dev.txt"
script:
  - coverage erase
  - coverage run tests/test_*.py && coverage html
after_success:
  - codecov
branches:
  only:
    - master
#deploy:
#  provider: elasticbeanstalk
#  access_key_id: "Encrypted <access-key-id>="
#  secret_access_key:
#    secure: "Encypted <secret-access-key>="
#  region: "us-east-1"
#  app: "example-app-name"
#  env: "example-app-environment"
#  bucket_name: "the-target-S3-bucket
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: AKIAI5MA6HN6MSXJWMSA
  secret_access_key: Be6PRpsYhg4kFIaHOsGKtRkT9i/VGcxSri7zt9HA
  application: baking-api
  deployment_group: staging
  region: "east-1"