language: python
python:
- '3.7'
install: pip install -r requirements/prd.txt
cache: pip
branches:
  only:
  - master
before_script:
- export PYTHONPATH=$PWD
- export APP_CONFIG_FILE=config/testing.py
- python baking/refresh_database.py
script:
- coverage erase
- coverage run baking/tests/test_general.py
- coverage run -a baking/tests/test_config.py
- coverage run -a baking/tests/test_songs.py
- coverage html
after_success:
- codecov
before_deploy:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
deploy:
  provider: heroku
  app: baking-lyrics
  strategy: git
  api_key:
    secure: NZxuCBS89CObRSeXdDfkDSHFLdggsgsbajLCAzXpkZRbXAd6h7NGbHq5K2gTBMZ6eDmSde0Y10czt1VQ7Cq7HSUNn7R5qjx4vtXI8Gnm2725CrFKUQJFQjBluhDaWmzFt/vSEYHweVNbWnk5JlIXzgCIRTdqMc5dh64I6wSwsRs9LLP/EXUpMrntmXhAI/+Div7ez8wBhRkJ91hUmk9Yp0VAs3X1YQCwK6H62ft8gxcUERvrAxYWwjP35fZcnDAr2A7bA4akS5GzhGMJFRYARtCcs9VBkVc0D+E7R81me1i1VXlPZtR1T5jn2aqDWjBHMuaYTNS0Xv+vYouzNZJ+7HVXzxKwpGj6MPBpuahCaP/D7+AQd0fOjp64b2jx/59n9qLM2nzqbd1tZ0EOTmLchqTPao8fTz1wGQD9Xmr3rNYq3RjsZYYwJvLsEhN7Lb4ygv8exXTO/an69/6A/uOVu5HI951PMHMDKjta5wmg6a34lADK8kX+RFCroV7UofODZEquXL3cJ41BDeTP7UME9e/AzSh9nDQNx2r6JWoysw1+PSZvIbzq48Orb2uGJ2hXF9DiKGqEDEpLWoV9i0Yi6J5XvEkVM0INZXq0Z7Ra8rdDm2E4S/7nzeF/gPQ2Oe8G+kZDijssuVQVqGk5gNuN+HJKVBlbJNFRH0fGEs6Zg6Q=
after_deploy:
#- "./start_api_prd.sh"
# AWS
#deploy:
#  - provider: s3
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
#    local_dir: dpl_cd_upload
#    skip_cleanup: true
#    on: &1
#      repo: arukavina/baking-lyrics
#    bucket: elasticbeanstalk-us-east-1-385336769428
#    region: "us-east-1"
#  - provider: codedeploy
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
#    bucket: elasticbeanstalk-us-east-1-385336769428
#    key: latest.zip
#    bundle_type: zip
#    application: ai.bakinglyrics.com
#    deployment_group: prd
#    region: "us-east-1"
#on: *1
# after_deploy:
# - ./start_api_prd.sh