language: python
python:
  - '3.6'
install: "pip install -r requirements/prd.txt"
cache: pip
branches:
  only:
    - master
before_script:
  - export PYTHONPATH=$PWD
  - python baking/refresh_database.py
script:
  - coverage erase
  - coverage run baking/tests/test_general.py
  - coverage run -a baking/tests/test_config.py
  - coverage run -a baking/tests/test_songs.py
  - coverage html
before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &1
      repo: arukavina/baking-lyrics
    bucket: elasticbeanstalk-us-east-1-385336769428
    region: "us-east-1"
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: elasticbeanstalk-us-east-1-385336769428
    key: latest.zip
    bundle_type: zip
    application: ai.bakinglyrics.com
    deployment_group: prd
    region: "us-east-1"
on: *1
after_deploy:
  - ./start_api_prd.sh