language: python
python:
- '3.7'
install: pip install -r requirements/prd.txt
cache: pip
branches:
  only:
  - master
before_script:
- export PYTHONPATH=$PWD
- export APP_CONFIG_FILE=config/testing.py
- python baking/refresh_database.py
script:
- coverage erase
- coverage run baking/tests/test_general.py
- coverage run -a baking/tests/test_config.py
- coverage run -a baking/tests/test_songs.py
- coverage html
after_success:
- codecov
before_deploy:
#- zip -r latest *
#- mkdir -p dpl_cd_upload
#- mv latest.zip dpl_cd_upload/latest.zip
deploy:
  provider: heroku
  app: baking-lyrics
  strategy: git
  api_key:
    secure: a1fryON3t/kNAIv8lrsGVBa8F0DBSTsOlc3UdEAtB0doa4Rjy8AikJqekR4muCatc6X2XFRrR1Swg8DPUp/L5cCiCF5iMQDJAQpUuM7XwV8ZDnU07wuozkrzcvzT7/IYXnBKGfbILuA+37HALI4lAf/nhLyZHkKPfTp5wC6Mf/gGIf2YNLYszwFylCLhzACjB/xyiZnv14q+6rXpbwqd2rDE62dUdRzpqtFVh9ubcUrLMjRoqqIuIHve+u2pH8q0bj/SzJZ0MG+gMz/9Gm9UNbVgRz9dvro9R4VSFQoykMtztPYj2rQgZcAYWFsUfFiew/df9lmK0BdMwdGvHhZL0KFYmDqbBfHHaLZIp+8pOlHFKkxxlxNmO092aNUOSbLdK3uqGXzxrSlJ41vsHLIPzZmxGKhB0kPQM3ifFvzeQxtm1U+Q829/2hEsoD7PpkFmf9wH7HdBCFJ2SNXqcOsleClY6NpJicTo+QiQwsb4FEJ/e9kAD/UEmjmRmupeSyvnluCZQoym2zMUuDR4AtDvEV6emWYnUEylOUk0Ok4UJJ1ixEJ9JlY38mKw5g/Z3mf9feRM9HuZI6idIUs9hNfyvKJ/kDbpybI4VIjQpVGlogNFntelfPMfulZYsckSDm+X4cMFytih4QFA5GE+X81u22HxlqgtPUfeiZPfPhziMEU=
after_deploy: 
