language: python
python:
  - '3.6'
install: "pip install -r requirements/prd.txt"
script:
  - coverage erase
  - coverage run baking/tests/test_general.py
  - coverage run -a baking/tests/test_config.py
  - coverage run -a baking/tests/test_songs.py
  - coverage html
branches:
  only:
    - master
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  application: baking-api
  deployment_group: staging
  region: "us-east-1"